---
- name: Testing initial on devzero.edu
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: vm1
       image: "bionic"
       key_name: automation-key
       timeout: 200
       flavor: 693b91b1-16b7-4e5b-a222-a5de94c7a34d
       auto_ip: no
       network: f9c6d59e-d492-442f-bb6c-91a374eeccf9
       security_groups: devzero_trust
       meta:
         os: ubuntu

  - name: Add second Server
    os_server:
       state: present
       name: vm2
       image: "centos 7"
       key_name: automation-key
       timeout: 200
       flavor: 693b91b1-16b7-4e5b-a222-a5de94c7a34d
       auto_ip: no
       network: f9c6d59e-d492-442f-bb6c-91a374eeccf9
       security_groups: devzero_trust
       meta:
         os: centos